/* Generated By:JavaCC: Do not edit this line. LoroIParserConstants.java */
package loro.parsers.javacc;

public interface LoroIParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 12;
  int FORMAL_COMMENT = 13;
  int MULTI_LINE_COMMENT = 14;
  int TEXT_DOC = 16;
  int GUIDE = 17;
  int IMPL = 18;
  int BOOLEANO = 19;
  int CADENA = 20;
  int CARACTER = 21;
  int ENTERO = 22;
  int REAL = 23;
  int ALGORITMO = 24;
  int BAJANDO = 25;
  int CASO = 26;
  int CICLO = 27;
  int CIERTO = 28;
  int CLASE = 29;
  int COMO = 30;
  int CONSTANTE = 31;
  int CONSTRUCTOR = 32;
  int CONTINUE = 33;
  int CREAR = 34;
  int DESDE = 35;
  int DESCRIPCION = 36;
  int EN = 37;
  int ENTONCES = 38;
  int ENTRADA = 39;
  int ES = 40;
  int ESPECIFICACION = 41;
  int ESTE = 42;
  int ESTRATEGIA = 43;
  int EXISTE = 44;
  int EXTIENDE = 45;
  int FALSO = 46;
  int FIN = 47;
  int GLOBAL = 48;
  int HAGA = 49;
  int HASTA = 50;
  int IMPLEMENTACION = 51;
  int INICIO = 52;
  int IMPLEMENTA = 53;
  int INTERFACE = 54;
  int METODO = 55;
  int MIENTRAS = 56;
  int NADA = 57;
  int NULO = 58;
  int OBJETO = 59;
  int OPERACION = 60;
  int PAQUETE = 61;
  int PARA = 62;
  int PARA_TODO = 63;
  int PASO = 64;
  int POS = 65;
  int PRE = 66;
  int REPITA = 67;
  int RETORNE = 68;
  int SALIDA = 69;
  int SEGUN = 70;
  int SI = 71;
  int SI_NO = 72;
  int SI_NO_si = 73;
  int SUPER = 74;
  int TERMINE = 75;
  int UTILIZA = 76;
  int LITERAL_ENTERO = 77;
  int LITERAL_REAL = 78;
  int EXPONENTE = 79;
  int HEXA = 80;
  int LITERAL_CARACTER = 81;
  int LITERAL_CADENA = 82;
  int ID = 83;
  int LETRA = 84;
  int DIGITO = 85;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;
  int IN_TEXT_DOC = 4;
  int IN_GUIDE = 5;
  int IN_IMPL = 6;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "\"\\\'\\\'\"",
    "\"{{\"",
    "\"{%\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 15>",
    "\"\\\'\\\'\"",
    "\"}}\"",
    "\"%}\"",
    "\"booleano\"",
    "\"cadena\"",
    "\"caracter\"",
    "\"entero\"",
    "\"real\"",
    "\"algoritmo\"",
    "\"bajando\"",
    "\"caso\"",
    "\"ciclo\"",
    "\"cierto\"",
    "\"clase\"",
    "\"como\"",
    "\"constante\"",
    "\"constructor\"",
    "<CONTINUE>",
    "\"crear\"",
    "\"desde\"",
    "<DESCRIPCION>",
    "\"en\"",
    "\"entonces\"",
    "\"entrada\"",
    "\"es_instancia_de\"",
    "<ESPECIFICACION>",
    "<ESTE>",
    "\"estrategia\"",
    "\"existe\"",
    "\"extiende\"",
    "\"falso\"",
    "\"fin\"",
    "\"global\"",
    "\"haga\"",
    "\"hasta\"",
    "<IMPLEMENTACION>",
    "\"inicio\"",
    "\"implementa\"",
    "\"interface\"",
    "<METODO>",
    "\"mientras\"",
    "\"nada\"",
    "\"nulo\"",
    "\"objeto\"",
    "<OPERACION>",
    "\"paquete\"",
    "\"para\"",
    "\"para_todo\"",
    "\"paso\"",
    "\"pos\"",
    "\"pre\"",
    "\"repita\"",
    "\"retorne\"",
    "\"salida\"",
    "<SEGUN>",
    "\"si\"",
    "\"si_no\"",
    "\"si_no_si\"",
    "\"super\"",
    "\"termine\"",
    "\"utiliza\"",
    "<LITERAL_ENTERO>",
    "<LITERAL_REAL>",
    "<EXPONENTE>",
    "<HEXA>",
    "<LITERAL_CARACTER>",
    "<LITERAL_CADENA>",
    "<ID>",
    "<LETRA>",
    "<DIGITO>",
    "\";\"",
    "\",\"",
    "\":\"",
    "\":=\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"->\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"/\"",
    "\"?\"",
    "\"<=>\"",
    "\"=>\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"%\"",
    "\"!\"",
    "\"~\"",
    "\"#\"",
    "\"@\"",
    "\".\"",
    "\"..\"",
    "\"::\"",
  };

}
